'use client'

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Lock, Shield, FileText, Download, Clock } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface AuditLog {
  id: string
  timestamp: string
  action: string
  user: string
  borrower: string
  details: string
  status: 'success' | 'pending' | 'failed'
  logType: 'system_activity' | 'consent_log'
  consentType?: string
}

const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    timestamp: '2024-01-20 10:30:45',
    action: 'Data Privacy Consent Given',
    user: 'john.doe@company.com',
    borrower: 'John Smith',
    details: 'Borrower consented to data processing and credit check',
    status: 'success',
    logType: 'consent_log',
    consentType: 'Data Privacy'
  },
  {
    id: '2',
    timestamp: '2024-01-20 10:28:15',
    action: 'Prediction Generated',
    user: 'john.doe@company.com',
    borrower: 'John Smith',
    details: 'ML model prediction generated with SHAP analysis',
    status: 'success',
    logType: 'system_activity'
  },
  {
    id: '3',
    timestamp: '2024-01-20 09:15:20',
    action: 'Data Privacy Consent Given',
    user: 'jane.smith@company.com',
    borrower: 'Jane Doe',
    details: 'Borrower consented to M-Pesa statement verification',
    status: 'success',
    logType: 'consent_log',
    consentType: 'M-Pesa Verification'
  },
  {
    id: '4',
    timestamp: '2024-01-20 09:10:00',
    action: 'Borrower Created',
    user: 'jane.smith@company.com',
    borrower: 'Jane Doe',
    details: 'New borrower profile created in system',
    status: 'success',
    logType: 'system_activity'
  },
  {
    id: '5',
    timestamp: '2024-01-19 16:45:10',
    action: 'Data Privacy Consent Given',
    user: 'bob.johnson@company.com',
    borrower: 'Bob Wilson',
    details: 'Borrower consented to data sharing with partners',
    status: 'success',
    logType: 'consent_log',
    consentType: 'Data Sharing'
  },
  {
    id: '6',
    timestamp: '2024-01-19 16:42:30',
    action: 'Data Viewed',
    user: 'bob.johnson@company.com',
    borrower: 'Bob Wilson',
    details: 'Borrower details accessed for review',
    status: 'success',
    logType: 'system_activity'
  },
]

export function AuditTrail() {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'success':
        return 'bg-green-500/10 text-green-700 dark:text-green-400'
      case 'pending':
        return 'bg-yellow-500/10 text-yellow-700 dark:text-yellow-400'
      case 'failed':
        return 'bg-red-500/10 text-red-700 dark:text-red-400'
      default:
        return ''
    }
  }

  const getLogIcon = (logType: string) => {
    switch (logType) {
      case 'consent_log':
        return <Lock className="h-4 w-4 text-blue-600" />
      case 'system_activity':
        return <FileText className="h-4 w-4 text-muted-foreground" />
      default:
        return null
    }
  }

  const getLogBadgeColor = (logType: string) => {
    switch (logType) {
      case 'consent_log':
        return 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300'
      case 'system_activity':
        return 'bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-300'
      default:
        return ''
    }
  }

  const consentLogs = mockAuditLogs.filter(log => log.logType === 'consent_log')
  const systemLogs = mockAuditLogs.filter(log => log.logType === 'system_activity')

  const downloadAuditReport = () => {
    const reportContent = `
AUDIT TRAIL REPORT
==================
Generated: ${new Date().toLocaleString()}

DATA PRIVACY CONSENT LOGS
-------------------------
${consentLogs.map(log => `
Timestamp: ${log.timestamp}
Action: ${log.action}
Consent Type: ${log.consentType}
User: ${log.user}
Borrower: ${log.borrower}
Details: ${log.details}
Status: ${log.status}
---`).join('\n')}

SYSTEM ACTIVITIES
-----------------
${systemLogs.map(log => `
Timestamp: ${log.timestamp}
Action: ${log.action}
User: ${log.user}
Borrower: ${log.borrower}
Details: ${log.details}
Status: ${log.status}
---`).join('\n')}

SUMMARY
-------
Total Consent Logs: ${consentLogs.length}
Total System Activities: ${systemLogs.length}
Total Events: ${mockAuditLogs.length}

Generated by Loan Evaluation System
    `

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportContent))
    element.setAttribute('download', `audit-trail-${Date.now()}.txt`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Audit Trail</h1>
          <p className="text-muted-foreground">Comprehensive logging of data privacy consents and system activities</p>
        </div>
        <Button onClick={downloadAuditReport} className="gap-2">
          <Download className="h-4 w-4" />
          Export Report
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lock className="h-5 w-5 text-blue-600" />
            Data Privacy Consent Logs
          </CardTitle>
          <CardDescription>All data privacy consents and authorizations</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {consentLogs.map((log) => (
              <div key={log.id} className="flex items-start gap-4 border-b border-border pb-4 last:border-0">
                <div className="mt-1 flex-shrink-0">
                  {getLogIcon(log.logType)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="font-medium text-foreground">{log.action}</h3>
                    <Badge variant="outline" className={getStatusColor(log.status)}>
                      {log.status}
                    </Badge>
                    <Badge className={getLogBadgeColor(log.logType)}>
                      {log.consentType || 'Consent'}
                    </Badge>
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">{log.details}</p>
                  <div className="mt-2 flex flex-wrap gap-4 text-xs text-muted-foreground">
                    <span><strong>User:</strong> {log.user}</span>
                    <span><strong>Borrower:</strong> {log.borrower}</span>
                    <span><strong>Time:</strong> {log.timestamp}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-muted-foreground" />
            System Activities
          </CardTitle>
          <CardDescription>All system operations and user actions</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {systemLogs.map((log) => (
              <div key={log.id} className="flex items-start gap-4 border-b border-border pb-4 last:border-0">
                <div className="mt-1 flex-shrink-0">
                  {getLogIcon(log.logType)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="font-medium text-foreground">{log.action}</h3>
                    <Badge variant="outline" className={getStatusColor(log.status)}>
                      {log.status}
                    </Badge>
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">{log.details}</p>
                  <div className="mt-2 flex flex-wrap gap-4 text-xs text-muted-foreground">
                    <span><strong>User:</strong> {log.user}</span>
                    <span><strong>Borrower:</strong> {log.borrower}</span>
                    <span><strong>Time:</strong> {log.timestamp}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Compliance Summary */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Consent Logs</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-blue-600" />
              <p className="text-2xl font-bold text-foreground">{consentLogs.length}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">System Activities</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              <p className="text-2xl font-bold text-foreground">{systemLogs.length}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Total Events</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <Clock className="h-5 w-5 text-muted-foreground" />
              <p className="text-2xl font-bold text-foreground">{mockAuditLogs.length}</p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
