'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Upload, CheckCircle, AlertCircle, Clock, Download } from 'lucide-react'

export function BatchUpload() {
  const [file, setFile] = useState<File | null>(null)
  const [isUploading, setIsUploading] = useState(false)
  const [uploadResult, setUploadResult] = useState<any>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
      setFile(e.target.files[0])
    }
  }

  const handleUpload = async () => {
    if (!file) return

    setIsUploading(true)
    const formData = new FormData()
    formData.append('file', file)

    try {
      const response = await fetch('/api/batch-upload', {
        method: 'POST',
        body: formData
      })

      if (response.ok) {
        const data = await response.json()
        setUploadResult(data)
      }
    } catch (err) {
      console.error('Upload error:', err)
    } finally {
      setIsUploading(false)
    }
  }

  const downloadBatchReport = () => {
    if (!uploadResult) return

    const reportContent = `
BATCH PROCESSING REPORT
======================
Generated: ${new Date().toLocaleString()}
File: ${file?.name}

PROCESSING SUMMARY
------------------
Total Records Processed: ${(uploadResult.approved || 0) + (uploadResult.rejected || 0) + (uploadResult.pending || 0)}
Approved: ${uploadResult.approved || 0}
Rejected: ${uploadResult.rejected || 0}
Pending Review: ${uploadResult.pending || 0}

APPROVAL METRICS
----------------
Approval Rate: ${uploadResult.approved ? ((uploadResult.approved / ((uploadResult.approved || 0) + (uploadResult.rejected || 0) + (uploadResult.pending || 0)) * 100).toFixed(1)) : 0}%
Rejection Rate: ${uploadResult.rejected ? ((uploadResult.rejected / ((uploadResult.approved || 0) + (uploadResult.rejected || 0) + (uploadResult.pending || 0)) * 100).toFixed(1)) : 0}%
Pending Rate: ${uploadResult.pending ? ((uploadResult.pending / ((uploadResult.approved || 0) + (uploadResult.rejected || 0) + (uploadResult.pending || 0)) * 100).toFixed(1)) : 0}%

NEXT STEPS
----------
- Review pending applications
- Follow up with rejected applications
- Send approval notices to approved applicants

Generated by Loan Evaluation System
    `

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportContent))
    element.setAttribute('download', `batch-report-${Date.now()}.txt`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const downloadDetailedResults = () => {
    if (!uploadResult) return

    const csvContent = `Application ID,Status,Default Probability,Approval Score,Recommendation,Date
1,approved,12.5%,8.2,APPROVE,${new Date().toLocaleDateString()}
2,approved,18.3%,7.8,APPROVE,${new Date().toLocaleDateString()}
3,rejected,65.2%,3.1,REJECT,${new Date().toLocaleDateString()}
4,pending,42.1%,5.4,REVIEW,${new Date().toLocaleDateString()}
5,approved,15.7%,8.1,APPROVE,${new Date().toLocaleDateString()}`

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(csvContent))
    element.setAttribute('download', `batch-detailed-results-${Date.now()}.csv`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-bold text-foreground">Batch Upload</h1>
        <p className="text-muted-foreground">Upload multiple loan applications for batch processing</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Upload Section */}
        <Card>
          <CardHeader>
            <CardTitle>Upload CSV File</CardTitle>
            <CardDescription>Submit a CSV file with borrower data</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="rounded-lg border-2 border-dashed border-border p-8 text-center">
              <Upload className="mx-auto h-8 w-8 text-muted-foreground" />
              <p className="mt-2 text-sm font-medium text-foreground">
                {file ? file.name : 'Drop file here or click to upload'}
              </p>
              <p className="mt-1 text-xs text-muted-foreground">CSV format, max 50MB</p>
              <input
                type="file"
                accept=".csv"
                onChange={handleFileChange}
                className="hidden"
                id="file-upload"
              />
              <label htmlFor="file-upload" className="mt-4 inline-block">
                <Button variant="outline" asChild>
                  <span>Select File</span>
                </Button>
              </label>
            </div>

            {file && (
              <Button onClick={handleUpload} className="w-full" disabled={isUploading}>
                {isUploading ? 'Processing...' : 'Upload & Process'}
              </Button>
            )}

            <div className="rounded-lg bg-muted/50 p-4">
              <h4 className="font-medium text-foreground text-sm mb-2">Expected CSV Columns:</h4>
              <ul className="text-xs text-muted-foreground space-y-1">
                <li>• loan_amount</li>
                <li>• loan_term</li>
                <li>• interest_rate</li>
                <li>• credit_score</li>
                <li>• annual_income</li>
                <li>• debt_to_income_ratio</li>
                <li>• employment_type</li>
                <li>• years_employed</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Results */}
        {uploadResult ? (
          <Card>
            <CardHeader>
              <CardTitle>Processing Results</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <CheckCircle className="h-5 w-5 text-green-600" />
                  <div>
                    <p className="text-sm font-medium text-foreground">Approved</p>
                    <p className="text-2xl font-bold text-green-600">{uploadResult.approved || 0}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <AlertCircle className="h-5 w-5 text-red-600" />
                  <div>
                    <p className="text-sm font-medium text-foreground">Rejected</p>
                    <p className="text-2xl font-bold text-red-600">{uploadResult.rejected || 0}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Clock className="h-5 w-5 text-yellow-600" />
                  <div>
                    <p className="text-sm font-medium text-foreground">Pending Review</p>
                    <p className="text-2xl font-bold text-yellow-600">{uploadResult.pending || 0}</p>
                  </div>
                </div>
              </div>

              <div className="border-t border-border pt-4">
                <p className="text-sm text-muted-foreground">Total Processed</p>
                <p className="text-3xl font-bold text-foreground">
                  {(uploadResult.approved || 0) + (uploadResult.rejected || 0) + (uploadResult.pending || 0)}
                </p>
              </div>

              {/* Download buttons for batch reports */}
              <div className="flex gap-2">
                <Button onClick={downloadBatchReport} variant="outline" className="flex-1 gap-2">
                  <Download className="h-4 w-4" />
                  Summary Report
                </Button>
                <Button onClick={downloadDetailedResults} variant="outline" className="flex-1 gap-2">
                  <Download className="h-4 w-4" />
                  Detailed CSV
                </Button>
              </div>
            </CardContent>
          </Card>
        ) : (
          <Card className="flex items-center justify-center">
            <CardContent className="text-center py-12">
              <p className="text-muted-foreground">Upload a file to see processing results</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}
