// ... existing code up to prediction results ...

import { ArrowLeft, Download, FileText } from 'lucide-react'

// ... existing borrower data ...

export function BorrowerDetail({ borrowerId }: { borrowerId: string }) {
  const [borrower] = useState<BorrowerData>({
    id: borrowerId,
    name: 'John Smith',
    email: 'john@example.com',
    phone: '+1 (555) 123-4567',
    loanAmount: 50000,
    loanTerm: 60,
    interestRate: 4.5,
    employment: 'Full-time Software Engineer',
    income: 120000,
    creditScore: 750,
    debtToIncomeRatio: 0.25,
    riskScore: 78,
    status: 'approved',
    createdAt: '2024-01-15'
  })

  const downloadBorrowerReport = () => {
    const reportContent = `
BORROWER DETAIL REPORT
====================
Generated: ${new Date().toLocaleString()}

PERSONAL INFORMATION
-------------------
Name: ${borrower.name}
Email: ${borrower.email}
Phone: ${borrower.phone}
Employment: ${borrower.employment}
Annual Income: $${borrower.income.toLocaleString()}

LOAN INFORMATION
----------------
Loan Amount: $${borrower.loanAmount.toLocaleString()}
Loan Term: ${borrower.loanTerm} months
Interest Rate: ${borrower.interestRate}%
Application Date: ${borrower.createdAt}

CREDIT PROFILE
--------------
Credit Score: ${borrower.creditScore}
Debt-to-Income Ratio: ${(borrower.debtToIncomeRatio * 100).toFixed(1)}%
Risk Score: ${borrower.riskScore}/100
Status: ${borrower.status.toUpperCase()}

ML PREDICTION RESULTS
--------------------
Default Probability: 12.5%
Recommendation: APPROVE
Approval Score: 8.2/10

FEATURE IMPORTANCE
------------------
Credit Score Impact: +12.5%
Income Level Impact: +8.2%
Debt-to-Income Impact: -5.3%
Employment History Impact: +4.1%
Loan Term Impact: -1.2%

Generated by Loan Evaluation System
    `

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportContent))
    element.setAttribute('download', `borrower-report-${borrower.name}-${borrower.id}.txt`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const downloadCreditAnalysis = () => {
    const analysisContent = `
CREDIT ANALYSIS REPORT
====================
Borrower: ${borrower.name}
Generated: ${new Date().toLocaleString()}

CREDIT WORTHINESS ASSESSMENT
----------------------------
Credit Score: ${borrower.creditScore}/850
Debt-to-Income Ratio: ${(borrower.debtToIncomeRatio * 100).toFixed(1)}%
Loan-to-Value Ratio: ${((borrower.loanAmount / borrower.income) * 100).toFixed(1)}%

RISK METRICS
-----------
Overall Risk Score: ${borrower.riskScore}/100
Risk Category: Low Risk

PAYMENT CAPACITY
---------------
Monthly Income: $${(borrower.income / 12).toLocaleString('en-US', { maximumFractionDigits: 2 })}
Estimated Loan Payment: $${((borrower.loanAmount * (borrower.interestRate / 100)) / (borrower.loanTerm / 12)).toLocaleString('en-US', { maximumFractionDigits: 2 })}
Payment to Income Ratio: ${(((borrower.loanAmount * (borrower.interestRate / 100)) / (borrower.loanTerm / 12)) / (borrower.income / 12) * 100).toFixed(1)}%

RECOMMENDATION
--------------
Status: ${borrower.status.toUpperCase()}
Suggested Terms: Standard lending terms with ${borrower.interestRate}% interest rate

Generated by Loan Evaluation System
    `

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(analysisContent))
    element.setAttribute('download', `credit-analysis-${borrower.name}-${Date.now()}.txt`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="space-y-6 p-6">
      <Link href="/dashboard/borrowers">
        <Button variant="ghost" className="gap-2">
          <ArrowLeft className="h-4 w-4" />
          Back to Borrowers
        </Button>
      </Link>

      <div>
        <h1 className="text-3xl font-bold text-foreground">{borrower.name}</h1>
        <p className="text-muted-foreground">{borrower.email}</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* ... existing personal information, loan info, credit cards ... */}
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle className="text-lg">Personal Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground">Email</p>
              <p className="font-medium text-foreground">{borrower.email}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Phone</p>
              <p className="font-medium text-foreground">{borrower.phone}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Employment</p>
              <p className="font-medium text-foreground">{borrower.employment}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Annual Income</p>
              <p className="font-medium text-foreground">${borrower.income.toLocaleString()}</p>
            </div>
          </CardContent>
        </Card>

        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle className="text-lg">Loan Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground">Loan Amount</p>
              <p className="font-medium text-foreground">${borrower.loanAmount.toLocaleString()}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Loan Term</p>
              <p className="font-medium text-foreground">{borrower.loanTerm} months</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Interest Rate</p>
              <p className="font-medium text-foreground">{borrower.interestRate}%</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Created</p>
              <p className="font-medium text-foreground">{borrower.createdAt}</p>
            </div>
          </CardContent>
        </Card>

        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle className="text-lg">Credit Profile</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <p className="text-sm text-muted-foreground">Credit Score</p>
              <p className="text-2xl font-bold text-primary">{borrower.creditScore}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Debt-to-Income Ratio</p>
              <p className="text-2xl font-bold text-primary">{(borrower.debtToIncomeRatio * 100).toFixed(1)}%</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Risk Score</p>
              <p className="text-2xl font-bold text-secondary">{borrower.riskScore}/100</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Status</p>
              <div className={`inline-block rounded-full px-3 py-1 text-sm font-medium capitalize ${
                borrower.status === 'approved'
                  ? 'bg-green-500/10 text-green-700 dark:text-green-400'
                  : 'bg-yellow-500/10 text-yellow-700 dark:text-yellow-400'
              }`}>
                {borrower.status}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>ML Prediction & SHAP Analysis</CardTitle>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="flex gap-2" onClick={downloadBorrowerReport}>
              <Download className="h-4 w-4" />
              Full Report
            </Button>
            <Button variant="outline" size="sm" className="flex gap-2" onClick={downloadCreditAnalysis}>
              <FileText className="h-4 w-4" />
              Credit Analysis
            </Button>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="rounded-lg border border-border p-4">
              <p className="text-sm font-medium text-muted-foreground">Default Probability</p>
              <p className="mt-2 text-3xl font-bold text-destructive">12.5%</p>
              <p className="mt-1 text-sm text-muted-foreground">Low risk of default</p>
            </div>
            <div className="rounded-lg border border-border p-4">
              <p className="text-sm font-medium text-muted-foreground">Recommendation</p>
              <p className="mt-2 text-lg font-bold text-green-600">APPROVE</p>
              <p className="mt-1 text-sm text-muted-foreground">With standard terms</p>
            </div>
          </div>

          <div className="mt-6">
            <h4 className="font-medium text-foreground">Feature Importance (SHAP)</h4>
            <div className="mt-4 space-y-3">
              {[
                { feature: 'Credit Score', importance: 0.35, contribution: '+12.5%' },
                { feature: 'Income Level', importance: 0.25, contribution: '+8.2%' },
                { feature: 'Debt-to-Income', importance: 0.20, contribution: '-5.3%' },
                { feature: 'Employment History', importance: 0.15, contribution: '+4.1%' },
                { feature: 'Loan Term', importance: 0.05, contribution: '-1.2%' },
              ].map((item, i) => (
                <div key={i} className="flex items-center justify-between">
                  <div className="flex flex-1 items-center gap-4">
                    <span className="text-sm font-medium text-foreground min-w-32">{item.feature}</span>
                    <div className="h-2 flex-1 rounded-full bg-muted">
                      <div
                        className="h-full rounded-full bg-primary"
                        style={{ width: `${item.importance * 100}%` }}
                      />
                    </div>
                  </div>
                  <span className={`text-sm font-medium ${item.contribution.startsWith('+') ? 'text-green-600' : 'text-red-600'}`}>
                    {item.contribution}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
