'use client'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'
import { Download } from 'lucide-react'

const dashboardData = [
  { name: 'Jan', approved: 45, rejected: 12, pending: 8 },
  { name: 'Feb', approved: 52, rejected: 14, pending: 6 },
  { name: 'Mar', approved: 48, rejected: 11, pending: 5 },
  { name: 'Apr', approved: 61, rejected: 15, pending: 7 },
  { name: 'May', approved: 58, rejected: 13, pending: 9 },
  { name: 'Jun', approved: 67, rejected: 16, pending: 4 },
]

const defaultRateData = [
  { name: 'Defaulted', value: 8 },
  { name: 'Current', value: 92 }
]

const COLORS = ['#dc2626', '#16a34a']

export function DashboardContent() {
  const totalLoans = 285
  const approvalRate = 78.2
  const avgScore = 72.5
  const defaultRate = 8

  const downloadDashboardReport = () => {
    const reportContent = `
LOAN EVALUATION DASHBOARD REPORT
================================
Generated: ${new Date().toLocaleString()}

KEY PERFORMANCE INDICATORS
---------------------------
Total Loans Evaluated: ${totalLoans}
Approval Rate: ${approvalRate}%
Average Credit Score: ${avgScore}
Default Rate: ${defaultRate}%

APPROVAL TRENDS (Monthly)
------------------------
January: 45 approved, 12 rejected, 8 pending
February: 52 approved, 14 rejected, 6 pending
March: 48 approved, 11 rejected, 5 pending
April: 61 approved, 15 rejected, 7 pending
May: 58 approved, 13 rejected, 9 pending
June: 67 approved, 16 rejected, 4 pending

PORTFOLIO COMPOSITION
--------------------
Current Loans: 92%
Defaulted Loans: 8%

APPLICATIONS BY STATUS
---------------------
Approved: 287 applications
Rejected: 81 applications
Pending: 39 applications

Generated by Loan Evaluation System
    `

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportContent))
    element.setAttribute('download', `dashboard-report-${Date.now()}.txt`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="space-y-8 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Dashboard</h1>
          <p className="text-muted-foreground">Welcome back! Here's your lending overview.</p>
        </div>
        <Button onClick={downloadDashboardReport} variant="outline" className="gap-2">
          <Download className="h-4 w-4" />
          Download Report
        </Button>
      </div>

      {/* KPI Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        {[
          { label: 'Total Loans Evaluated', value: totalLoans, color: 'primary' },
          { label: 'Approval Rate', value: `${approvalRate}%`, color: 'secondary' },
          { label: 'Avg Credit Score', value: avgScore, color: 'accent' },
          { label: 'Default Rate', value: `${defaultRate}%`, color: 'destructive' },
        ].map((kpi, i) => (
          <Card key={i}>
            <CardHeader className="pb-2">
              <CardDescription>{kpi.label}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className={`text-2xl font-bold text-${kpi.color}`}>
                {kpi.value}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Charts */}
      <div className="grid gap-6 lg:grid-cols-2">
        {/* Approval Trend */}
        <Card>
          <CardHeader>
            <CardTitle>Approval Trend</CardTitle>
            <CardDescription>Monthly loan approvals over time</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <LineChart data={dashboardData}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
                <XAxis dataKey="name" stroke="var(--color-muted-foreground)" />
                <YAxis stroke="var(--color-muted-foreground)" />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'var(--color-card)',
                    border: '1px solid var(--color-border)',
                    borderRadius: 'var(--radius)'
                  }}
                />
                <Legend />
                <Line type="monotone" dataKey="approved" stroke="var(--color-primary)" strokeWidth={2} />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Default Rate */}
        <Card>
          <CardHeader>
            <CardTitle>Default Rate</CardTitle>
            <CardDescription>Current portfolio performance</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <PieChart>
                <Pie
                  data={defaultRateData}
                  cx="50%"
                  cy="50%"
                  labelLine={false}
                  label={({ name, value }) => `${name}: ${value}%`}
                  outerRadius={80}
                  fill="#8884d8"
                  dataKey="value"
                >
                  {defaultRateData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      {/* Applications by Status */}
      <Card>
        <CardHeader>
          <CardTitle>Applications by Status</CardTitle>
          <CardDescription>Distribution of loan applications</CardDescription>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={dashboardData}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
              <XAxis dataKey="name" stroke="var(--color-muted-foreground)" />
              <YAxis stroke="var(--color-muted-foreground)" />
              <Tooltip
                contentStyle={{
                  backgroundColor: 'var(--color-card)',
                  border: '1px solid var(--color-border)',
                  borderRadius: 'var(--radius)'
                }}
              />
              <Legend />
              <Bar dataKey="approved" fill="var(--color-primary)" />
              <Bar dataKey="rejected" fill="var(--color-destructive)" />
              <Bar dataKey="pending" fill="var(--color-muted)" />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>
    </div>
  )
}
